export const BG_THEMES = [
  {
    label: "다크",
    presets: [
      { label: "기본",       value: "#161616" },
      { label: "미드나잇",   value: "#08080f" },
      { label: "슬레이트",   value: "#111820" },
      { label: "딥그레이",   value: "#0e0e0e" },
      { label: "챠콜",      value: "#1a1a1a" },
      { label: "네이비",     value: "#0d1b2a" },
      { label: "퍼플",      value: "#1a1228" },
      { label: "포레스트",   value: "#0d1f10" },
      { label: "버건디",     value: "#220d0d" },
      { label: "틸",        value: "#0d1f1e" },
      { label: "인디고",     value: "#141232" },
      { label: "에스프레소", value: "#130c08" },
    ],
  },
  {
    label: "파스텔",
    presets: [
      { label: "베이비블루", value: "#b8d4e8" },
      { label: "라벤더",    value: "#c8b8e8" },
      { label: "민트",      value: "#b8e0d4" },
      { label: "피치",      value: "#f0c8b4" },
      { label: "로즈",      value: "#f0b8c8" },
      { label: "레몬",      value: "#e8e4a8" },
      { label: "라일락",    value: "#d4b8e0" },
      { label: "아쿠아",    value: "#a8d8e0" },
      { label: "살몬",      value: "#f0c4b4" },
      { label: "스카이",    value: "#b4d0f0" },
      { label: "세이지",    value: "#b8d4b8" },
      { label: "코랄",      value: "#f0b8a8" },
    ],
  },
  {
    label: "라이트",
    presets: [
      { label: "화이트",    value: "#f0f0f0" },
      { label: "크림",      value: "#f5f0e8" },
      { label: "웜그레이",  value: "#d8d4ce" },
      { label: "실버",      value: "#e0e0e8" },
      { label: "미스트",    value: "#dce8f0" },
      { label: "아이보리",  value: "#f8f4ec" },
      { label: "라이트민트", value: "#e0f0ec" },
      { label: "라이트피치", value: "#f5e8e0" },
      { label: "라이트라벤더", value: "#ede8f5" },
      { label: "클라우드",  value: "#eaecf0" },
      { label: "샌드",      value: "#ede8dc" },
      { label: "스노우",    value: "#f8f8f8" },
    ],
  },
];
